name: Build impedance.py
description: Composite workflow to re-use the build of impedance.py using poetry.
inputs:
  python-version:
    description: python version used for setup-python.
    required: false
    default: 3.7

env:
  POETRY-VERSION: 1.1.14

runs:
  using: composite
  steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        shell: bash
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version ${{ env.POETRY-VERSION }}
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH  # add poetry to PATH.

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'  # needs setup-python@v4, speeds up building

      - name: Install poetry and dependencies
        shell: bash
        run: |
          poetry env use ${{ env.python-version }}
          poetry install
