name: CI tests
on:
  pull_request:
  push:
    branches:
      - main
env:
  OS-VERSION: ubuntu-latest

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build_impedance

      - name: Linting with flake8
        run: poetry run flake8 . --count --show-source --exclude=*.ipynb_checkpoints

  tests:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/build_impedance
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests with pytest
        run: poetry run pytest --cov=impedance .

      - name: Upload coverage to coveralls
        if: matrix.python-version == 3.7 && github.repository == 'ECSHackWeek/impedance.py'
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
